services:
  postgres:
    image: postgres
    container_name: greenlight_postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
