CREATETABLEIFNOTEXISTSmovies(
    id bigserialPRIMARYKEY,
    created_atTIMESTAMP(0)WITHTIMEZONENOTNULLDEFAULTNOW(),
    titleTEXTNOTNULLYEARINTEGERNOTNULL,
    runtimeINTEGERNOTNULL,
    genresTEXT[]NOTNULL,
    versionINTEGERNOTNULLDEFAULT1
);
